[package]
name = "near-transactions-generator"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
near-primitives = { workspace = true, features = ["clock"] }

[lints]
workspace = true
